<?xml version="1.0" encoding="utf-8"?><Database Name="TAREADW" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.CLIENTES" Member="CLIENTES">
    <Type Name="CLIENTES">
      <Column Name="CODIGO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SALDO" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTOS" Member="PRODUCTOS">
    <Type Name="PRODUCTOS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CODIGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="COSTO" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="PRECIO" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="STOCK" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PROVEEDORES" Member="PROVEEDORES">
    <Type Name="PROVEEDORES">
      <Column Name="CODIGO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="APELLIDO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CORREO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SALDO" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>